### ISSUE TITLE
drop in replacement for cheerio?

### ISSUE THREAD

**Issue by andykais** [nuxodin/domProxy#2]
Hi! I just ran into this lib and had a few questions:
- Can this be used in node?
- If so, can it replace cheerio?
- What kind of benchmarks does this library have (compared to say cheerio and jquery)

**Comment by nuxodin** [comment]
Hi Andy

In node, you can used it with jsdom i think.

The primary goal is to have some little helpers to make DOM easier to handle. 
This with as little overhead as possible. (The goal is to stay below 1k)

An example: 
Instead of writing this:
```js
document.querySelector('h2').forEach(el=>{
    el.addEventListener('click', handleEvent);
    el.addEventListener('focus', handleEvent);
})
```

You write this.
```js
$('h2').on('click focus', handleEvent)
```

This library is quite new, i have no benchmarks yet.

**Comment by andykais** [comment]
got it. Good luck then, and thanks for the quick reply!
